from typing import Optional, List, Tuple

from core.meta.singleton import Singleton


class StreamingPlatforms(metaclass=Singleton):
    """
    流媒体平台简称与全称。
    """
    STREAMING_PLATFORMS: List[Tuple[str, str]] = [
        ("AMZN", "Amazon"),
        ("NF", "Netflix"),
        ("ATVP", "Apple TV+"),
        ("iT", "iTunes"),
        ("DSNP", "Disney+"),
        ("HS", "Hotstar"),
        ("PMTP", "Paramount+"),
        ("HMAX", "Max"),
        ("", "Max"),
        ("HULU", "Hulu Networks"),
        ("MA", "Movies Anywhere"),
        ("BCORE", "Bravia Core"),
        ("MS", "Microsoft Store"),
        ("SHO", "Showtime"),
        ("STAN", "Stan"),
        ("PCOK", "Peacock"),
        ("SKST", "SkyShowtime"),
        ("NOW", "Now"),
        ("FXTL", "Foxtel Now"),
        ("BNGE", "Binge"),
        ("CRKL", "Crackle"),
        ("RKTN", "Rakuten TV"),
        ("ALL4", "Channel 4"),
        ("MUBI", "Mubi"),
        ("PLAY", "Google Play"),
        ("YT", "YouTube"),
        ("Hami", "Hami Video"),
        ("HamiVideo", "Hami Video"),
        ("MW", "meWATCH"),
        ("CATCHPLAY", "CATCHPLAY+"),
        ("CPP", "CATCHPLAY+"),
        ("LINETV", "LINE TV"),
        ("VIU", "Viu"),
        ("ABMA", "Abema"),
        ("ADN", ""),
        ("AT-X", ""),
        ("BG", "B-Global"),
        ("CR", "Crunchyroll"),
        ("Crunchy Roll", "Crunchyroll"),
        ("FOD", ""),
        ("FUNi", "Funimation"),
        ("HIDI", "HIDIVE"),
        ("UNXT", "U-NEXT"),
        ("iP", "BBC iPlayer"),
        ("ROKU", "Roku"),
        ("VIKI", "Rakuten Viki"),
        ("PLEX", "Plex"),
        ("CRAV", "Crave"),
        ("VIAP", "Viaplay"),
        ("TUBI", "TubiTV"),
        ("PBS", ""),
        ("PBSK", "PBS KIDS"),
        ("MP", "Movistar Plus+"),
        ("STZ", "STARZ"),
        ("FUBO", "fuboTV"),
        ("CW", "The CW"),
        ("FOX", ""),
        ("ITVX", "ITV"),
        ("HBO", "HBO"),
        ("HBOGO", "HBO GO"),
        ("EPIX", "EPIX MGM+"),
        ("SYFY", "SyFy"),
        ("DISC", "Discovery Channel"),
        ("NATG", "National Geographic"),
        ("NICK", "Nickelodeon"),
        ("BBC", ""),
        ("DW", "DailyWire+"),
        ("DLWP", "DailyWire+"),
        ("PlutoTV", "Pluto TV"),
        ("AbemaTV", "Abema"),
        ("TVER", "TVer"),
        ("VIDIO", "Vidio"),
        ("WAVVE", "Wavve"),
        ("WAKA", "Wakanim"),
        ("WAKANIM", "Wakanim"),
        ("AO", "AnimeOnegai"),
        ("OV", "OceanVeil"),
        ("AMZ", "Amazon"),
        ("Amazon Prime", "Amazon"),
        ("Prime Video", "Amazon"),
        ("PrimeVideo", "Amazon"),
        ("PV", "Amazon"),
        ("NFX", "Netflix"),
        ("NFLX", "Netflix"),
        ("ATV", "Apple TV+"),
        ("AppleTV+", "Apple TV+"),
        ("AppleTVPlus", "Apple TV+"),
        ("Apple TV Plus", "Apple TV+"),
        ("DPLUS", "Disney+"),
        ("DisneyPlus", "Disney+"),
        ("Disney Plus", "Disney+"),
        ("HBO Max", "Max"),
        ("HBOMax", "Max"),
        ("HBOM", "Max"),
        ("ParamountPlus", "Paramount+"),
        ("Paramount Plus", "Paramount+"),
        ("PPLUS", "Paramount+"),
        ("PARA", "Paramount+"),
        ("Peacock TV", "Peacock"),
        ("PeacockTV", "Peacock"),
        ("YouTube Premium", "YouTube"),
        ("YouTubePremium", "YouTube"),
        ("YTP", "YouTube"),
        ("Discovery+", "Discovery+"),
        ("DiscoveryPlus", "Discovery+"),
        ("Discovery Plus", "Discovery+"),
        ("DSCP", "Discovery+"),
        ("AMC+", "AMC+"),
        ("AMCPlus", "AMC+"),
        ("AMC Plus", "AMC+"),
        ("MGM+", "MGM+"),
        ("MGMPlus", "MGM+"),
        ("MGM Plus", "MGM+"),
        ("BritBox", "BritBox"),
        ("Acorn TV", "Acorn TV"),
        ("AcornTV", "Acorn TV"),
        ("Shudder", "Shudder"),
        ("CraveTV", "Crave"),
        ("Roku Channel", "Roku"),
        ("RokuChannel", "Roku"),
        ("BILI", "Bilibili"),
        ("Bilibili", "Bilibili"),
        ("BiliBili", "Bilibili"),
        ("Bilibili Global", "B-Global"),
        ("BGlobal", "B-Global"),
        ("IQ", "iQIYI"),
        ("IQIYI", "iQIYI"),
        ("iQIYI", "iQIYI"),
        ("WeTV", "WeTV"),
        ("Tencent", "WeTV"),
        ("Tencent Video", "WeTV"),
        ("TencentVideo", "WeTV"),
        ("TXTV", "WeTV"),
        ("YOUKU", "Youku"),
        ("Youku", "Youku"),
        ("MGTV", "MangoTV"),
        ("MangoTV", "MangoTV"),
        ("Mango TV", "MangoTV"),
        ("Migu", "Migu Video"),
        ("Migu Video", "Migu Video"),
        ("Sohu", "Sohu Video"),
        ("Sohu Video", "Sohu Video"),
        ("LeTV", "LeTV"),
        ("PPTV", "PPTV"),
        ("Baha", "Bahamut Anime"),
        ("Bahamut", "Bahamut Anime"),
        ("Bahamut Anime", "Bahamut Anime"),
        ("AniGamer", "Bahamut Anime"),
        ("friDay", "friDay Video"),
        ("Friday", "friDay Video"),
        ("friDay Video", "friDay Video"),
        ("Friday Video", "friDay Video"),
        ("KKTV", "KKTV"),
        ("LiTV", "LiTV"),
        ("MyVideo", "MyVideo"),
        ("GagaOOLala", "GagaOOLala"),
        ("ELTA", "ELTA TV"),
        ("ELTA TV", "ELTA TV"),
        ("Ani-One", "Ani-One"),
        ("AniOne", "Ani-One"),
        ("Ani One", "Ani-One"),
        ("Ani-One Asia", "Ani-One"),
        ("AniOne Asia", "Ani-One"),
        ("Muse", "Muse Asia"),
        ("Muse Asia", "Muse Asia"),
        ("MuseTW", "Muse Asia"),
        ("Muse Taiwan", "Muse Asia"),
        ("DMM", "DMM TV"),
        ("DMM TV", "DMM TV"),
        ("Lemino", "Lemino"),
        ("TELASA", "TELASA"),
        ("WOWOW", "WOWOW"),
        ("Niconico", "Niconico"),
        ("NicoNico", "Niconico"),
        ("Nico", "Niconico"),
        ("Bandai Channel", "Bandai Channel"),
        ("BANDAI", "Bandai Channel"),
        ("AnimeFesta", "AnimeFesta"),
        ("TVING", "TVING"),
        ("Coupang", "Coupang Play"),
        ("Coupang Play", "Coupang Play"),
        ("CoupangPlay", "Coupang Play"),
        ("Watcha", "Watcha"),
        ("Laftel", "Laftel"),
        ("KakaoTV", "KakaoTV"),
        ("Kakao TV", "KakaoTV"),
        ("Naver TV", "Naver TV"),
        ("NaverTV", "Naver TV"),
        ("TrueID", "TrueID"),
        ("AISPLAY", "AIS PLAY"),
        ("AIS PLAY", "AIS PLAY"),
        ("iWantTFC", "iWantTFC"),
        ("Channel4", "Channel 4"),
        ("All4", "Channel 4"),
        ("All 4", "Channel 4"),
        ("NowTV", "Now"),
        ("Now TV", "Now"),
        ("iPlayer", "BBC iPlayer"),
        ("My5", "My5"),
        ("5OD", "My5"),
        ("RTL+", "RTL+"),
        ("RTLPlus", "RTL+"),
        ("RTL Plus", "RTL+"),
        ("Joyn", "Joyn"),
        ("ARD", "ARD"),
        ("ZDF", "ZDF"),
        ("Arte", "Arte"),
        ("Canal+", "Canal+"),
        ("CanalPlus", "Canal+"),
        ("Canal Plus", "Canal+"),
        ("TF1", "TF1"),
        ("FranceTV", "FranceTV"),
        ("France TV", "FranceTV"),
        ("ABC iView", "ABC iView"),
        ("iView", "ABC iView"),
        ("SBS On Demand", "SBS On Demand"),
        ("SBS", "SBS On Demand"),
        ("10Play", "10 Play"),
        ("10 Play", "10 Play"),
        ("9Now", "9Now"),
        ("7Plus", "7Plus"),
        ("7 Plus", "7Plus"),
    ]

    def __init__(self):
        self._lookup_cache = {}
        self._build_cache()

    def _build_cache(self) -> None:
        self._lookup_cache.clear()
        for short_name, full_name in self.STREAMING_PLATFORMS:
            canonical_name = full_name or short_name
            if not canonical_name:
                continue
            aliases = {short_name, full_name}
            for alias in aliases:
                if alias:
                    self._lookup_cache[alias.upper()] = canonical_name

    def get_streaming_platform_name(self, platform_code: str) -> Optional[str]:
        if platform_code is None:
            return None
        return self._lookup_cache.get(platform_code.upper())

    def is_streaming_platform(self, name: str) -> bool:
        if name is None:
            return False
        return name.upper() in self._lookup_cache
